### PR TITLE
[Windows] cmake for ded

### PR DESCRIPTION
**Pull request by GmosNM**
its working for me on [WINDOWS]
idk if it will work on anything else

### CODE REVIEW

**Comment by BillKek** [comment]
Trying `cmake -G "MinGW Makefiles"` for generate Makefile for MSYS2 mingw tools, but get: 
`... dependencies/glfw" which is not an existing directory.`
Is this cmake only for the Microsoft compiler?

**Comment by GmosNM** [comment]
@BillKek the setup_dependencies.bat is not working ig, just download freetype and add it to the deps folder
[https://sourceforge.net/projects/freetype/files/freetype2/2.13.0/]

**Comment by BillKek** [comment]
> setup_dependencies

The `Msys2` already has all libraries inside. I thought the `cmake` script will automatically find them in the standard `mingw` folder. I thought the syntax of the `cmake` script gives universality automatically, but sadly the magic doesn't work.(((

**Comment by GmosNM** [comment]
@BillKek try cmake -G Ninja -B bld

**Comment by BillKek** [comment]
> cmake -G Ninja -B bld

...
`-- Detecting C compile features - done`
`-- Found OpenGL: opengl32`
`-- Found Freetype: C:/msys64/mingw64/lib/libfreetype.dll.a (found version "2.12.1")`
`-- Found GLEW: C:/msys64/mingw64/lib/cmake/glew/glew-config.cmake`
`CMake Error at CMakeLists.txt:21 (add_subdirectory):`
`add_subdirectory given source`
`"C:/XXX/tsoding/gmosnm1/ded-master/dependencies/SDL2" which`
`is not an existing directory.`                                                                                                                                                                                                                                                                         `CMake Error at CMakeLists.txt:25 (add_subdirectory):`
`add_subdirectory given source`
`"C:/XXX/tsoding/gmosnm1/ded-master/dependencies/glfw" which`
`is not an existing directory.`

Failed. But `SDL2` and `glfw` are available inside Msys2+Mingw :
`pacman -S mingw-w64-x86_64-SDL2`
`warning: mingw-w64-x86_64-SDL2-2.26.2-1 is up to date -- reinstalling`
`pacman -S mingw-w64-x86_64-glfw`
`warning: mingw-w64-x86_64-glfw-3.3.8-2 is up to date -- reinstalling`

**Comment by theoparis** [comment]
You could try using `find_package` to to use the system-installed versions of SDL2 and glfw3.

**Pull request closed without merging**
